### ISSUE TITLE
Postgres error 

### ISSUE THREAD

**Issue by NobilisNC** [ned-kelly/docker-multicontainer-libretime#15]
Hello,

I tried to run `docker-compose up -d` but I have this error.

```
libretime-postgres    | ERROR:  relation "cc_pref" does not exist at character 72
libretime-postgres    | STATEMENT:  SELECT cc_pref.id, cc_pref.subjid, cc_pref.keystr, cc_pref.valstr FROM cc_pref WHERE cc_pref.keystr=$1 LIMIT 1
```

**Comment by frecuencialibre** [comment]
did this happen upon fresh container creation or on subsequent iterations? 

I've seen errors like this too, which I've guessed are caused by the Libretime database tables etc. not existing due to the install script not having run. I haven't yet taken the time troubleshoot, but in my case docker was re-creating containers from existing caches, and also I'd touched the `postgresql` folder on the host machine where the `libretime-postgres` container stores data.

**Comment by ned-kelly** [comment]
If this is a new install - and you don't mind losing your old files, try blowing away your working directly  and then re-cloning this project and re-installing ... otherwise, you can manually remove the `postgresql` - you will lose all references to any media you've uploaded and libretime configurations however.

**Comment by falcon03** [comment]
@ned-kelly having the same issue on a fresh installation, any ideas on what might be causing the problem?

**Comment by funkeeflow** [comment]
Hi Guys, having the same issue, any hints any this?

**Comment by ballPointPenguin** [comment]
same issue on fresh installation.
Is there a database migration script that needs to be run?

**Comment by ballPointPenguin** [comment]
Looking at the libretime database in pgAdmin, it appears to have no tables. Somewhere a step to create the db tables is being skipped? I'm not sure where/when that is supposed to happen.

**Comment by paqstd-dev** [comment]
@ned-kelly I have the same problem. I deleted the entire folder several times. Need to help

**Comment by crudexec** [comment]
same issue any help here @ned-kelly

**Comment by newuser0109** [comment]
same issue with fresh intall is there any older docker image that works

**Comment by BhagatHarsh** [comment]
Still getting same issue with fresh install, is there a solution to this?
