### ISSUE TITLE
3 libretime instances

### ISSUE THREAD

**Issue by WeigandM** [ned-kelly/docker-multicontainer-libretime#19]
I have a question, how can I run 3 or more libretime instances on a dedicated without them getting in the way? I have several IP addresses that could be used (if necessary).

**Comment by ned-kelly** [comment]
If you're happy to share the database (which I would) and just use a different database name then you will need to:

 * Run multiple Libretime containers - each will need a different WEB_UI_PORT, MASTER_SOURCE_PORT, and DJ_SOURCE_PORT port that's not conflicting
 * Run multiple Icecast containers on different ports - each corresponding Libretime host will then need to obvoiusly be configured to use it's matching Icecast container
 * Run multiple RabbitMQ containers (this will be the easiest option) and configure each libretime to talk to it's own RMQ container.

The container actually tries to "initialise" the database & RMQ if it's empty when it first starts, so you will need to make some changes in the `bootstrap/firstrun.sh` file...

The easiest thing will be to modify the [`bootstrap/entrypoint.sh`](https://github.com/ned-kelly/docker-multicontainer-libretime/blob/master/bootstrap/entrypoint.sh#L66) file to actually exclude the first-run line (comment it out) so that way you're presented with the Libretime configuration screen when you start the container for the first time.

Once you've done this edit your [`docker-compose.yml`](https://github.com/ned-kelly/docker-multicontainer-libretime/blob/master/docker-compose.yml#L71-L81) file to build the image, rather than pull the pre-built image we've got published from Docker Hub

Should be pretty easy to setup once you've done some testing -
